### ISSUE TITLE
The live demo is broken

### ISSUE THREAD

**Issue by greenido** [googlecodelabs/polymer-offline-weather#3]
https://googlecodelabs.github.io/polymer-offline-weather/final/index.html

when I open the console I see: 
The FetchEvent for "https://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%2…%20WHERE%20text%3D%2237.4209397%2C-122.0934599%22%20and%20gflags%3D%22R%22)" resulted in a network error response: an object that was not a Response was passed to respondWith().
https://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%2…20WHERE%20text%3D%2237.4209397%2C-122.0934599%22%20and%20gflags%3D%22R%22) Failed to load resource: net::ERR_FAILED

**Comment by bovas85** [comment]
up, can anyone fix this?

**Comment by beaufortfrancois** [comment]
@jeffposnick Can you have a look?

**Comment by jeffposnick** [comment]
Thanks for the ping—somehow I wasn't already Watching this repo 😦 

I believe something was deprecated or otherwise changed with the underlying API calls. I'll try the approach mentioned at http://stackoverflow.com/questions/34904938/yahoo-yql-query-with-gflags-returns-nothing to see if that helps.

**Comment by bovas85** [comment]
Glad to help, I'll try that

**Comment by bovas85** [comment]
I've tried using geoplaces(1) but it returns useless data for what the purpose is here. There has to be a better query using lat-long or maybe we need to first get the location and then query that later.

**Comment by jeffposnick** [comment]
Right, I think it might need to happen in two separate API calls, as described in this answer: http://stackoverflow.com/a/34920208/385997

**Comment by bovas85** [comment]
actually nevermind, I didn't remove gflags. It now returns 
https://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(SELECT%20woeid%20FROM%20geo.places(1)%20WHERE%20text%3D%22(51.504500699999994%2C-0.035201199999999995)%22)

**Comment by bovas85** [comment]
sent you guys a pull request
